# Generated by Django 5.0.2 on 2024-02-14 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.AddField(
            model_name='orderline',
            name='car',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservice.car'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
