# Generated by Django 5.0.2 on 2024-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_car_cover_alter_car_vin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='service',
        ),
        migrations.AddField(
            model_name='orderline',
            name='services',
            field=models.ManyToManyField(to='autoservice.service'),
        ),
    ]
